<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FsF_Cast" Id="{7cb5674f-4a26-42ab-9d1c-aa55fb2ada02}" SpecialFunc="None">
    <Declaration><![CDATA[// Casts an object of that implements FsI_Object to another type of object.
FUNCTION FsF_Cast : REFERENCE TO FsFB_Error
VAR_INPUT
	ipFrom : FsI_Object;
	ipTo : FsI_Object;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF ipFrom = 0 OR_ELSE ipTo = 0 THEN 
	FsF_Cast REF= FsF_Error(FsGVL_ErrorCodes.INVALID_INTERFACE, 'Null interface casting. You cannot cast to or from a null interface.');
	RETURN; 
	END_IF
	
IF ipFrom.Size <> ipTo.Size THEN
	FsF_Cast REF= FsF_Error(FsGVL_ErrorCodes.SIZE_MISMATCH, 'Size mismatch. The sizes of the casting entities do not match.');
	RETURN;
	END_IF
	
Tc2_System.MEMCPY(FsF_GetAddress(ipTo), FsF_GetAddress(ipFrom), TO_UDINT(ipFrom.Size));
FsF_Cast REF= FsF_Error(FsGVL_ErrorCodes.NO_ERROR, '');]]></ST>
    </Implementation>
    <LineIds Name="FsF_Cast">
      <LineId Id="18" Count="0" />
      <LineId Id="25" Count="5" />
      <LineId Id="32" Count="0" />
      <LineId Id="31" Count="0" />
      <LineId Id="49" Count="0" />
      <LineId Id="41" Count="0" />
      <LineId Id="50" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>