<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FsF_IecApplicationInformation" Id="{c801c14f-c7fb-4dfb-a113-f15126d5b18d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION FsF_IecApplicationInformation : ITcIecApplicationInfo]]></Declaration>
    <Implementation>
      <ST><![CDATA[FW_ObjMgr_GetObjectInstance(TwinCAT_SystemInfoVarList._AppInfo.ObjId, TC_GLOBAL_IID_LIST.IID_ITcIecApplicationInfo, ADR(FsF_IecApplicationInformation));]]></ST>
    </Implementation>
    <LineIds Name="FsF_IecApplicationInformation">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>