<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FsFB_Object" Id="{b9a7d797-4e3c-4bd7-a9f4-98928c915162}" SpecialFunc="None">
    <Declaration><![CDATA[// Base class of all classes in the FisoThemes Standard Library.
{attribute 'enable_dynamic_creation'}
{attribute 'no_assign'}
{attribute 'no_explicit_call' := 'direct call for this function block is not allowed'} 
FUNCTION_BLOCK FsFB_Object IMPLEMENTS FsI_Object
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Methods" Id="{e0c51f80-3b85-4e15-968a-5fe33c64a10d}" />
    <Folder Name="Properties" Id="{4cfd352d-4987-4e1b-8453-bbe171753889}" />
    <Method Name="FB_init" Id="{5a15df2b-2053-43e1-92ac-307f29102340}">
      <Declaration><![CDATA[{attribute 'hide'}
{attribute 'no_explicit_call' := 'direct call for this method is not allowed'} 
METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FsFB_Object">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FsFB_Object.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>