<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="_MAIN" Id="{8e6ddbe0-2456-42a2-8b16-7085c8b833c4}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INTERNAL _MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FsP_CorePlayground();]]></ST>
    </Implementation>
    <LineIds Name="_MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>