<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="FsP_CorePlayground" Id="{fe32e6f4-2a42-43f5-bef2-f3cbb688e3ff}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INTERNAL FsP_CorePlayground
VAR
	fbObj : FsT_Obj;
	sSymName : STRING(255) := FsF_GetTypeNameByAddress(ADR(fbObj), SIZEOF(fbObj));
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FsP_CorePlayground">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>